name: Atualizar calendário IMDb

on:
  schedule:
    - cron: '0 6 * * 5'  # toda sexta-feira às 6h UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Gerar arquivo calendar.ics
        run: python generate.py

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Commit e push do arquivo atualizado
        run: |
          git add calendar.ics
          git commit -m "Atualização automática do calendário" || echo "Nada para commitar"
          git push
