name: Atualizar calendário IMDb

on:
  schedule:
    - cron: "0 7 * * 1"  # toda segunda-feira às 7h UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests beautifulsoup4 ics

      - name: Gerar calendário
        run: python generate.py

      - name: Fazer commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add calendar.ics
          git commit -m "Atualização automática do calendário"
          git push
